apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP